### PR TITLE
feat(backport): upgrade, cleanup before backport from caas

### PR DESCRIPTION
**Pull request by haarchri**
### Description of your changes
- upgrade build module
- bump uptest
- bump up-cli
- remove outdated pictures without reference to documents
- switch package to apis
- update makefile
- stop running publish action in forks without ci variable

Fixes #

I have:

- [x] Read and followed Upbound's [contribution process](https://git.io/fj2m9).
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added `backport release-x.y` labels to auto-backport this PR, as appropriate.

### CODE REVIEW

**Comment by ytsarev** [comment]
@haarchri uptest failed here

**Comment by haarchri** [comment]
problem is that an resource group `platform-ref-azure-rg` still exists - and this platform-ref-azure is not generating the resource group with an random hash - this is fixed in caas - will check to cleanup the pre-existing `platform-ref-azure-rg
 `

**Comment by haarchri** [comment]
local run:

```
--- PASS: kuttl (1526.62s)
    --- PASS: kuttl/harness (0.00s)
        --- PASS: kuttl/harness/case (1525.39s)
PASS
09:14:04 [ OK ] running automated tests
```

**Comment by haarchri** [comment]
okay the issue here is: 

```
lastTransitionTime: "2023-10-27T07:24:38Z"
message: 'observe failed: cannot run refresh: refresh failed: building account:
  could not acquire access token to parse claims: clientCredentialsToken: received
  HTTP status 401 with response: ***"error":"invalid_client","error_description":"AADSTS7000222:
  The provided client secret keys for app ''86d55993-6f8b-4012-8201-5a9dceb8b327''
  are expired. Visit the Azure portal to create new keys for your app: https://aka.ms/NewClientSecret,
  or consider using certificate credentials for added security:
```

**Review by ytsarev — APPROVED** [review]
Thanks for fixing the credentials issue, LGTM

**Pull request merged**
